/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.clientroznica.visualforms;

import com.mycompany.clientroznica.datamodels.TableRecord;
import com.mycompany.clientroznica.datamodels.EditListModel;
import com.mycompany.clientroznica.datamodels.TableData;
import com.mycompany.clientroznica.entity.GlassForShop;
import com.mycompany.clientroznica.entity.Sklad;
import com.mycompany.clientroznica.repositories.GlassForShopRepository;
import com.mycompany.clientroznica.repositories.SkladRepository;
import java.awt.Dialog;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import java.util.ArrayList;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;
import java.util.Vector;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Component;

/**
 *
 * @author Евгений
 */

@Component

public class MainFrame extends javax.swing.JFrame {

    @Autowired
    private SkladRepository skladRepository;
    
    @Autowired
    private GlassForShopRepository glassForShopRepository;
    
    @Autowired
    private SelectFromEditList selectFromEditList;
    
    @Autowired
    private EditListModel editListModel;
    
    @Autowired
    private TableData tableData;
    
    private List<GlassForShop> itemsForSearch;
    private JList templateListForChoise=new JList();
    private JScrollPane templateScrollPane=new JScrollPane(templateListForChoise);
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        add(templateScrollPane,0);
        templateListForChoise.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode()==KeyEvent.VK_ENTER){
                    findText.setText(templateListForChoise.getSelectedValue().toString());
                    templateScrollPane.setVisible(false);
                    templateListForChoise.setVisible(false);
                    findText.grabFocus();
                }
            }
        });
        templateListForChoise.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent e){
                if(!e.getOppositeComponent().equals(findText)){
                    templateScrollPane.setVisible(false);
                    templateListForChoise.setVisible(false);
                }
            }
        });
        findText.addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent e){
                if(!e.getOppositeComponent().equals(templateListForChoise)){
                    templateScrollPane.setVisible(false);
                    templateListForChoise.setVisible(false);
                }
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        skladLabel = new javax.swing.JLabel();
        skladCombo = new javax.swing.JComboBox();
        findLabel = new javax.swing.JLabel();
        findText = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        skladLabel.setText("Склад:");

        findLabel.setText("Найти:");

        findText.setText("Введите строку для поиска");
        findText.setSelectionStart(0);
        findText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTextActionPerformed(evt);
            }
        });
        findText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                findTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                findTextKeyTyped(evt);
            }
        });

        newButton.setText("Добавить");

        jScrollPane1.setViewportView(dataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(findLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(findText))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(skladLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(skladCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skladLabel)
                    .addComponent(skladCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findLabel)
                    .addComponent(findText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Iterable<Sklad> sklads= new TreeSet<Sklad>();
        sklads=skladRepository.findAll(new Sort(Sort.Direction.ASC,"name"));
        
        skladCombo.removeAllItems();
        for(Sklad sklad:sklads){
            skladCombo.addItem(sklad);
        }
        dataTable.setModel(tableData);
        dataTable.getColumnModel().getColumn(0).setMinWidth(0);
        dataTable.getColumnModel().getColumn(0).setPreferredWidth(4);
        dataTable.getColumnModel().getColumn(1).setPreferredWidth(282);
        dataTable.getColumnModel().getColumn(3).setPreferredWidth(4);
        dataTable.getColumnModel().getColumn(4).setPreferredWidth(10);
        
    }//GEN-LAST:event_formWindowOpened

    private void findTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findTextKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_DOWN&&templateListForChoise.isVisible()){
            templateListForChoise.grabFocus();
            templateListForChoise.setSelectedIndex(0);
        }
    }//GEN-LAST:event_findTextKeyPressed

    private void findTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTextActionPerformed
        if (findText.getText()!=""){
            ArrayList <GlassForShop> glassForShops=(ArrayList)glassForShopRepository.findByNameLikeOrderByNameAsc(findText.getText()+"%");
            editListModel.setList((ArrayList)glassForShops);
            selectFromEditList.editList.setModel(editListModel);
            selectFromEditList.setModal(true);
            selectFromEditList.setVisible(true);
            if (selectFromEditList.getSelectedItem()>-1){
                GlassForShop item=glassForShops.get(selectFromEditList.getSelectedItem());
                int row=((TableData)dataTable.getModel()).add(new TableRecord(item.getName(),item.getBarcode(), 1, item.getPrice()));
                dataTable.repaint();
                dataTable.editCellAt(row, 3);
                ((JTextField)dataTable.getEditorComponent()).selectAll();
                dataTable.grabFocus();
            }
            
        }
    }//GEN-LAST:event_findTextActionPerformed

    private void findTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findTextKeyTyped
        
        String findString=findText.getText()+evt.getKeyChar();
        if((findString.length()==2)||(findString.length()>2&&!templateListForChoise.isVisible())){
            itemsForSearch= glassForShopRepository.findByNameLikeOrderByNameAsc(findString+"%");
        }
        if(findString.length()>1){

            editListModel.setList((ArrayList)getNameByPrefix(findString));
            
            templateListForChoise.setModel(editListModel);
            
            templateScrollPane.setBounds(findText.getBounds().x, findText.getBounds().y+findText.getBounds().height,maxLength(itemsForSearch)*5,100);
            templateListForChoise.setBounds(findText.getBounds().x, findText.getBounds().y+findText.getBounds().height,maxLength(itemsForSearch)*5,100);
            templateListForChoise.setVisibleRowCount(10);
            templateScrollPane.setVisible(true);
            templateListForChoise.setVisible(true);
            
//            templateListForChoise.grabFocus();
            repaint();
        }
    }//GEN-LAST:event_findTextKeyTyped

    private List<GlassForShop> getNameByPrefix(String prefix) {
        List<GlassForShop> result=new ArrayList<GlassForShop>();
        for(GlassForShop item:itemsForSearch){
            if(item.getName().startsWith(prefix))
                result.add(item);
        }
        return result;
    }
    
    private int maxLength(List<GlassForShop> items){
        int result=0;
        for(GlassForShop item:items){
            if(item.getName().length()>result)
                result=item.getName().length();
        }
        return result;
    }
    
    private String generateNewBarcode(String name){
        int num=1;
        
	String SQL=String.format("select max(substr(bar_code,%s,5)) from bar_code where bar_code like '%s%s'", (new Integer(group)).toString().length()+1,group,"%");
	if (special){
            SQL=String.format("select max(substr(barcode,%s,5)) from glassforshop where barcode like '%s%s'", (new Integer(group)).toString().length()+1,group,"%");
	}	
        ResultSet rs=DataSet.QueryExec1(SQL, false);
        if (rs.next())
        num=rs.getInt(1);
        String code=String.format("%s%05d", group,num+1);
        String code_sum=String.format("%07d%05d", group,num+1);

        Integer sum=new Integer(0);
        for (int i=2;i<13;i=i+2)
            sum=sum+(Integer.valueOf(code_sum.substring(i-1, i)));
        sum=sum*3;
        for (int i=1;i<12;i=i+2)
            sum=sum+(Integer.valueOf(code_sum.substring(i-1, i)));
        sum=10-((Double)((((sum.doubleValue()/10)-sum/10)*10)+0.1)).intValue();
        code=code+sum.toString().substring(sum.toString().length()-1);
        return code;

        return null;
        }
            
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel findLabel;
    private javax.swing.JTextField findText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JComboBox skladCombo;
    private javax.swing.JLabel skladLabel;
    // End of variables declaration//GEN-END:variables
}
